sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: MATRIX_ENV="CC=gcc-6 && CXX=g++-6"
    
before_install:
  - eval $MATRIX_ENV

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make -f tests/Makefile
  - ./tests/run_tests

